version: "3.8"
services:
  redis:
    image: "bitnami/redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier

  server:
    build: pe-server/
    container_name: pe-server
    ports:
      - "8080:8080"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
